/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as autheddashboardRouteRouteImport } from './routes/(authed)/(dashboard)/route'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as autheddashboardIndexRouteImport } from './routes/(authed)/(dashboard)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as autheddashboardWeddingsIndexRouteImport } from './routes/(authed)/(dashboard)/weddings/index'
import { Route as autheddashboardWeddingsWeddingIdIndexRouteImport } from './routes/(authed)/(dashboard)/weddings/$weddingId/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const autheddashboardRouteRoute = autheddashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => authedRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const autheddashboardIndexRoute = autheddashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => autheddashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const autheddashboardWeddingsIndexRoute =
  autheddashboardWeddingsIndexRouteImport.update({
    id: '/weddings/',
    path: '/weddings/',
    getParentRoute: () => autheddashboardRouteRoute,
  } as any)
const autheddashboardWeddingsWeddingIdIndexRoute =
  autheddashboardWeddingsWeddingIdIndexRouteImport.update({
    id: '/weddings/$weddingId/',
    path: '/weddings/$weddingId/',
    getParentRoute: () => autheddashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof autheddashboardIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/weddings/': typeof autheddashboardWeddingsIndexRoute
  '/weddings/$weddingId/': typeof autheddashboardWeddingsWeddingIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof autheddashboardIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/weddings': typeof autheddashboardWeddingsIndexRoute
  '/weddings/$weddingId': typeof autheddashboardWeddingsWeddingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authed)': typeof authedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(authed)/(dashboard)': typeof autheddashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authed)/(dashboard)/': typeof autheddashboardIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/(authed)/(dashboard)/weddings/': typeof autheddashboardWeddingsIndexRoute
  '/(authed)/(dashboard)/weddings/$weddingId/': typeof autheddashboardWeddingsWeddingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/api/auth/$'
    | '/'
    | '/auth/login/'
    | '/auth/sign-up/'
    | '/weddings/'
    | '/weddings/$weddingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/api/auth/$'
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/weddings'
    | '/weddings/$weddingId'
  id:
    | '__root__'
    | '/(authed)'
    | '/auth'
    | '/(authed)/(dashboard)'
    | '/api/auth/$'
    | '/(authed)/(dashboard)/'
    | '/auth/login/'
    | '/auth/sign-up/'
    | '/(authed)/(dashboard)/weddings/'
    | '/(authed)/(dashboard)/weddings/$weddingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authedRouteRoute: typeof authedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/(dashboard)': {
      id: '/(authed)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof autheddashboardRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(authed)/(dashboard)/': {
      id: '/(authed)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof autheddashboardIndexRouteImport
      parentRoute: typeof autheddashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/(dashboard)/weddings/': {
      id: '/(authed)/(dashboard)/weddings/'
      path: '/weddings'
      fullPath: '/weddings/'
      preLoaderRoute: typeof autheddashboardWeddingsIndexRouteImport
      parentRoute: typeof autheddashboardRouteRoute
    }
    '/(authed)/(dashboard)/weddings/$weddingId/': {
      id: '/(authed)/(dashboard)/weddings/$weddingId/'
      path: '/weddings/$weddingId'
      fullPath: '/weddings/$weddingId/'
      preLoaderRoute: typeof autheddashboardWeddingsWeddingIdIndexRouteImport
      parentRoute: typeof autheddashboardRouteRoute
    }
  }
}

interface autheddashboardRouteRouteChildren {
  autheddashboardIndexRoute: typeof autheddashboardIndexRoute
  autheddashboardWeddingsIndexRoute: typeof autheddashboardWeddingsIndexRoute
  autheddashboardWeddingsWeddingIdIndexRoute: typeof autheddashboardWeddingsWeddingIdIndexRoute
}

const autheddashboardRouteRouteChildren: autheddashboardRouteRouteChildren = {
  autheddashboardIndexRoute: autheddashboardIndexRoute,
  autheddashboardWeddingsIndexRoute: autheddashboardWeddingsIndexRoute,
  autheddashboardWeddingsWeddingIdIndexRoute:
    autheddashboardWeddingsWeddingIdIndexRoute,
}

const autheddashboardRouteRouteWithChildren =
  autheddashboardRouteRoute._addFileChildren(autheddashboardRouteRouteChildren)

interface authedRouteRouteChildren {
  autheddashboardRouteRoute: typeof autheddashboardRouteRouteWithChildren
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  autheddashboardRouteRoute: autheddashboardRouteRouteWithChildren,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authedRouteRoute: authedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
